// <auto-generated />
using System;
using Ilary.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ilary.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251211220337_ActualizarEntidadesJobApplication")]
    partial class ActualizarEntidadesJobApplication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ilary.Domain.Entities.Coder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RolesId");

                    b.ToTable("Coder");
                });

            modelBuilder.Entity("Ilary.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NIT")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RolesId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Ilary.Domain.Entities.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CoderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoderId");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("Ilary.Domain.Entities.Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Ilary.Domain.Entities.Coder", b =>
                {
                    b.HasOne("Ilary.Domain.Entities.Roles", null)
                        .WithMany("Coder")
                        .HasForeignKey("RolesId");
                });

            modelBuilder.Entity("Ilary.Domain.Entities.Company", b =>
                {
                    b.HasOne("Ilary.Domain.Entities.Roles", null)
                        .WithMany("Company")
                        .HasForeignKey("RolesId");
                });

            modelBuilder.Entity("Ilary.Domain.Entities.JobApplication", b =>
                {
                    b.HasOne("Ilary.Domain.Entities.Coder", null)
                        .WithMany("JobApplication")
                        .HasForeignKey("CoderId");

                    b.HasOne("Ilary.Domain.Entities.Company", null)
                        .WithMany("JobApplication")
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("Ilary.Domain.Entities.Coder", b =>
                {
                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("Ilary.Domain.Entities.Company", b =>
                {
                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("Ilary.Domain.Entities.Roles", b =>
                {
                    b.Navigation("Coder");

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
